config/routes.rb
class ShortUrlMatcher
  def self.matches?(request)
    request.path.exclude?('.')
  end
end

Rails.application.routes.draw do
  get ':short_url', to: 'redirects#get_node', constraints: ShortUrlMatcher
  get 'images/:short_url', to: 'redirects#get_pixel'

  root 'home#welcome'


  scope :app do

    resource :session

    resources :nodes, param: :short_url
    resources :pixels, param: :short_url

    resources :hits, only: :destroy
    resources :users, param: :username

  end

  namespace :api, defaults: { format: :json } do
    resources :nodes, param: :short_url do
      resources :hits, only: :index
    end

    resources :pixels, param: :short_url do
      resources :hits, only: :index
    end
  end

  get '*node_redirect_url', to: 'nodes#new', format: false

end

app/models/node.rb
class Node < ActiveRecord::Base

  include Urlable

  validates_presence_of :redirect_url

  belongs_to :user
  has_many :hits, as: :hittable, dependent: :destroy

  SHORT_URL_LENGTH = 6

  def full_url
    "#{ENV['DOMAIN']}/#{short_url}"
  end

  def redirect_url_with_scheme
    return redirect_url if URI.parse(redirect_url).scheme
    'http://' + redirect_url
  end

end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController

  before_action :ensure_signed_in, only: :index

  def new
    @node = Node.new(redirect_url: build_redirect_from_url)
  end

  def create
    @node = Node.new(create_params)
    @node.user = current_user

    if @node.save
      flash[:notice] = 'url created!'
      redirect_to node_path(@node.short_url)
    else
      flash_errors(@node)
      render :new
    end
  end

  def show
    @node = Node.find_by_short_url(params[:short_url])
    raise ActionController::RoutingError.new(:short_url) unless @node
    @hits = @node.hits
  end

  def index
    @nodes = current_user.nodes.includes(:hits)
  end

  private

  def create_params
    attrs = [:redirect_url]
    attrs.push(:short_url) if current_user.try(:admin?)
    params.require(:node).permit(*attrs)
  end

  def build_redirect_from_url
    redirect_url = params[:node_redirect_url]
    return unless redirect_url
    redirect_url += "?#{request.query_string}" if request.query_string.present?
    redirect_url
  end

end

app/views/nodes/_node.html.haml
- hit_count = node.hits.count

%td
  = node.full_url
%td
  %button.copy-button{"data-clipboard-text" => "#{node.full_url}"}
    Copy link
%td
  = link_to node.redirect_url, node.redirect_url_with_scheme
%td
  = link_to "(#{hit_count} hits)", node_path(node.short_url)

app/views/nodes/index.html.haml
%h3
  My URLs

%table.nodes-table
  - @nodes.each do |node|
    %tr
      = render 'node', node: node

%br
= link_to 'create url', new_node_path

app/views/nodes/new.html.haml
%h1
  New link

%br
= form_for @node do |form|

  = form.label :redirect_url, 'Full url'
  %br
  = form.text_field :redirect_url

  - if current_user.try(:admin?)
    %br
    = form.label :short_url, 'Short url'
    %br
    = form.text_field :short_url

  %br
  %br

  = submit_tag "shorten"

app/views/nodes/show.html.haml
= render 'node', node: @node

%br

= render 'hits/node_index'