config/routes.rb
class ShortUrlMatcher
  def self.matches?(request)
    request.path.exclude?('.')
  end
end

Rails.application.routes.draw do
  get ':short_url', to: 'redirects#get_node', constraints: ShortUrlMatcher
  get 'images/:short_url', to: 'redirects#get_pixel'

  root 'home#welcome'


  scope :app do

    resource :session

    resources :nodes, param: :short_url
    resources :pixels, param: :short_url

    resources :hits, only: :destroy
    resources :users, param: :username

  end

  namespace :api, defaults: { format: :json } do
    resources :nodes, param: :short_url do
      resources :hits, only: :index
    end

    resources :pixels, param: :short_url do
      resources :hits, only: :index
    end
  end

  get '*node_redirect_url', to: 'nodes#new', format: false

end

app/models/pixel.rb
class Pixel < ActiveRecord::Base

  include Urlable

  validates_presence_of :user, :name

  has_many :hits, as: :hittable, dependent: :destroy
  belongs_to :user

  SHORT_URL_LENGTH = 8

  def full_url
    "#{ENV['DOMAIN']}/images/#{short_url}"
  end

  def image_tag
    "<img src='http://#{full_url}'>"
  end

end

app/controllers/pixels_controller.rb
class PixelsController < ApplicationController

  before_action :ensure_signed_in

  def new
    @pixel = Pixel.new
  end

  def create
    @pixel = Pixel.new(create_params.merge(
      user: current_user
    ))

    if @pixel.save
      flash[:notice] = 'Tracking pixel created!'
      redirect_to pixel_path(@pixel.short_url)
    else
      flash_errors(@pixel)
      render :new
    end
  end

  def show
    @pixel = Pixel.find_by_short_url(params[:short_url])
    @hits = @pixel.hits
  end

  def index
    @pixels = current_user.pixels.includes(:hits)
  end

  private

  def create_params
    params.require(:pixel).permit(:name, :description)
  end


end

app/views/pixels/index.html.haml
%h3
  my tracking pixels

= "#{@pixels.count} total pixels"

- if @pixels.any?
  %table.pixels-table.pretty-table
    %tr
      %td Name
      %td Description
      %td Hits

    - @pixels.each do |pixel|
      %tr
        %td
          = link_to pixel.name, pixel_path(pixel.short_url)
        %td= pixel.description
        %td
          = link_to "(#{pixel.hits.count} hits)", pixel_path(pixel.short_url)



%br
%br

= link_to 'create tracking pixel', new_pixel_path

app/views/pixels/new.html.haml
%h3
  New tracking pixel

%br

= form_for @pixel do |form|

  = form.label :name
  %br
  = form.text_field :name, placeholder: 'name this pixel'

  %br
  %br

  = form.label :description
  %br
  = form.text_area :description, placeholder: "more information (eg. 'email to steve')", width: 100

  %br

  = submit_tag 'create tracking pixel'

app/views/pixels/show.html.haml
%h4
  = @pixel.name

- if @pixel.description.present?
  = @pixel.description
  %br
= @pixel.created_at.strftime("%A, %B %d, %Y at %I:%M %p")
%br
%br

= @pixel.full_url

%button.copy-button{"data-clipboard-text" => @pixel.image_tag}
  Copy image tag

%br

or copy this ->
#{@pixel.image_tag.html_safe}
<-

%br
%br

= render 'hits/pixel_index'