config/routes.rb
class ShortUrlMatcher
  def self.matches?(request)
    request.path.exclude?('.')
  end
end

Rails.application.routes.draw do
  get ':short_url', to: 'redirects#get_node', constraints: ShortUrlMatcher
  get 'images/:short_url', to: 'redirects#get_pixel'

  root 'home#welcome'


  scope :app do

    resource :session

    resources :nodes, param: :short_url
    resources :pixels, param: :short_url

    resources :hits, only: :destroy
    resources :users, param: :username

  end

  namespace :api, defaults: { format: :json } do
    resources :nodes, param: :short_url do
      resources :hits, only: :index
    end

    resources :pixels, param: :short_url do
      resources :hits, only: :index
    end
  end

  get '*node_redirect_url', to: 'nodes#new', format: false

end

app/models/hit.rb
class Hit < ActiveRecord::Base
  belongs_to :hittable, polymorphic: true

  validates_presence_of :hittable, :hittable_type

  IGNORE_THRESHOLD = 1.minute

  LOCATION_ATTRS = %w(latitude longitude city)

  def location=(location_attrs)
    assign_attributes(location_attrs.slice(*LOCATION_ATTRS))
  end
end

app/controllers/api/hits_controller.rb
class Api::HitsController < ApplicationController

  before_filter :allow_cors

  def index
    hittable = if short_url = params[:node_short_url]
      Node.find_by_short_url(short_url)
    elsif short_url = params[:pixel_short_url]
      Pixel.find_by_short_url(short_url)
    end

    @hits = hittable.hits

    get_hits_data
  end

  private

  def get_hits_data
    @serialized_hits = @hits.order(:created_at).map { |h| HitSerializer.new(h).as_json }
    @count = @hits.size
    @timeline = @serialized_hits.map { |h| h[:timestamp] }
    @uniq_hits = @hits.group(:meta).count.count
    @referer = request.referer
  end

end

app/controllers/hits_controller.rb
class HitsController < ApplicationController

  def destroy
    if params[:hittable_type] == Node.name
      current_user.node_hits.find(params[:id])
    elsif params[:hittable_type] == Pixel.name
      current_user.pixel_hits.find(params[:id])
    end.destroy

    render json: {success: true, id: params[:id]}
  end

end

app/views/hits/_index.html.haml
%table.hit-index-table.pretty-table
  %tr
    %th ip
    %th time
    %th meta
    %th delete

  - @hits.each do |hit|
    %tr.js-hit-row{data: {hit: hit.id}}
      %td
        = hit.ip
      %td
        = hit.created_at.strftime("%A, %B %d, %Y at %I:%M %p")
      %td
        = hit.meta
      %td
        %button.hit-destroy-button{data: { url: hit_path(hit), hittable_type: hittable_type }}
          delete

app/views/hits/_node_index.html.haml
= "#{@hits.count} hits for "
= link_to @node.short_url, node_path(@node.short_url)

- if @hits.present?
  = render partial: 'hits/index', locals: { hittable_type: Node.name }

app/views/hits/_pixel_index.html.haml
= "#{@hits.count} hits for "
= link_to @pixel.name, pixel_path(@pixel.short_url)

- if @hits.present?
  = render partial: 'hits/index', locals: { hittable_type: Pixel.name }

app/views/hits/node_index.html.haml
= "#{@hits.count} hits for "
= link_to @node.short_url, node_path(@node.short_url)

- if @hits.present?
  = render partial: 'index', locals: { hitable_type: Node.name }

app/views/hits/pixel_index.html.haml
= "#{@hits.count} hits for "
= link_to @pixel.name, pixel_path(@pixel.short_url)

- if @hits.present?
  = render partial: 'index', locals: { hitable_type: Pixel.name }