config/routes.rb
class ShortUrlMatcher
  def self.matches?(request)
    request.path.exclude?('.')
  end
end

Rails.application.routes.draw do
  get ':short_url', to: 'redirects#get_node', constraints: ShortUrlMatcher
  get 'images/:short_url', to: 'redirects#get_pixel'

  root 'home#welcome'


  scope :app do

    resource :session

    resources :nodes, param: :short_url
    resources :pixels, param: :short_url

    resources :hits, only: :destroy
    resources :users, param: :username

  end

  namespace :api, defaults: { format: :json } do
    resources :nodes, param: :short_url do
      resources :hits, only: :index
    end

    resources :pixels, param: :short_url do
      resources :hits, only: :index
    end
  end

  get '*node_redirect_url', to: 'nodes#new', format: false

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title AriHost
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .header
      .header-content
        = link_to '/' do
          %span.app-title
            ari.host
        %span.header-links.js-header-links
          - if current_user
            %span.header-link
              #{current_user.username}
            %span.header-link
              = link_to 'my urls', nodes_path
            %span.header-link
              = link_to 'my tracking pixels', pixels_path
            %span.header-link
              = link_to 'sign out', session_path, method: :delete
          - else
            %span.header-link
              = link_to 'sign in', new_session_path
            %span.header-link
              = link_to 'create account', new_user_path

      .main-content
        .main-content-body
          - if flash[:errors]
            .flash-errors
              %ul
                - flash[:errors].each do |err|
                  %li
                    = err

          - [:notice, :error].each do |flash_type|
            - if flash[flash_type]
              .flash-message{class: flash_type}
                = flash[flash_type]
              %br


          = yield